# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_mei11'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mei12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/')),
            ],
        ),
        migrations.AlterField(
            model_name='mei11',
            name='image',
            field=models.ImageField(upload_to='static/', width_field=123),
        ),
    ]
