# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_mei13'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mei14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.GenericIPAddressField()),
            ],
        ),
    ]
