# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_mei15'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mei16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
