# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20160626_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mei16',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mei16',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
