# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20160626_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='mei16',
            name='fa',
            field=models.CharField(choices=[('1', 'haoren'), ('2', 'huairen')], default=1, max_length=12),
        ),
    ]
