# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20160626_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mei16',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
