# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(blank=True, default='', max_length=255)),
                ('faceurl', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('keywords', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('poster', models.CharField(blank=True, default='', max_length=255)),
                ('videourl', models.CharField(blank=True, default='', max_length=255)),
                ('videotime', models.IntegerField(blank=True, default=0)),
                ('arttype', models.IntegerField(blank=True, default=1)),
                ('status', models.IntegerField(blank=True, default=1)),
                ('fid', models.IntegerField(blank=True, default=0)),
                ('viewnumber', models.IntegerField(blank=True, default=0)),
                ('commentnumber', models.IntegerField(blank=True, default=0)),
                ('imagenumber', models.IntegerField(blank=True, default=0)),
                ('createtime', models.IntegerField(blank=True, default=0)),
                ('updatetime', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default='', max_length=255)),
                ('keywords', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('faceurl', models.CharField(blank=True, default='', max_length=255)),
                ('arttype', models.IntegerField(blank=True, default=1)),
                ('status', models.IntegerField(blank=True, default=1)),
                ('artnumber', models.IntegerField(blank=True, default=0)),
                ('createtime', models.IntegerField(blank=True, default=0)),
                ('updatetime', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(blank=True, default='', max_length=255)),
                ('iurl', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.IntegerField(blank=True, default=1)),
                ('fid', models.IntegerField(blank=True, default=0)),
                ('aid', models.IntegerField(blank=True, default=0)),
                ('createtime', models.IntegerField(blank=True, default=0)),
                ('updatetime', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('faceurl', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.IntegerField(blank=True, default=1)),
                ('createtime', models.IntegerField(blank=True, default=0)),
                ('updatetime', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
