# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160627_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='createtime',
        ),
    ]
