# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160702_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='quet',
            name='tt2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
