# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_quet_tt2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(default='', max_length=255)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=255)),
                ('total', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='inv',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Pro'),
        ),
    ]
