# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160702_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cy',
            name='xm',
            field=models.ManyToManyField(to='blog.Xm'),
        ),
        migrations.AlterField(
            model_name='inv',
            name='project2',
            field=models.CharField(choices=[('xm2', 'dianxin'), ('xm1', 'shiyou')], default='', max_length=255),
        ),
    ]
