# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160702_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kname', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Xs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xname', models.CharField(default='', max_length=255)),
                ('xm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Kp')),
            ],
        ),
    ]
