# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_base_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='base',
            name='createtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inv',
            name='project2',
            field=models.CharField(choices=[('xm1', 'shiyou'), ('xm2', 'dianxin')], default='', max_length=255),
        ),
    ]
