# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160702_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv',
            name='project2',
            field=models.CharField(choices=[('xm2', 'dianxin'), ('xm1', 'shiyou')], default='', max_length=255),
        ),
    ]
