# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160702_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv',
            name='project2',
            field=models.CharField(choices=[('xm1', 'shiyou'), ('xm2', 'dianxin')], default='', max_length=255),
        ),
    ]
