# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20160704_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv',
            name='project2',
            field=models.CharField(choices=[('xm1', 'shiyou'), ('xm2', 'dianxin')], default='', max_length=255),
        ),
    ]
