# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_ren1_laoshi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ren1',
            name='face',
            field=models.ImageField(default='/', upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='ren1',
            name='laoshi',
            field=models.CharField(choices=[('c', 'yuwen'), ('b', 'wuli'), ('a', 'shuxue')], default='a', max_length=100),
        ),
    ]
