# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20160626_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ren4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ren1',
            name='laoshi',
            field=models.CharField(choices=[('a', 'shuxue'), ('c', 'yuwen'), ('b', 'wuli')], default='a', max_length=100),
        ),
    ]
