# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_auto_20160702_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ren1',
            name='laoshi',
            field=models.CharField(choices=[('b', 'wuli'), ('a', 'shuxue'), ('c', 'yuwen')], default='a', max_length=100),
        ),
    ]
