# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_auto_20160704_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ren1',
            name='laoshi',
            field=models.CharField(choices=[('a', 'shuxue'), ('b', 'wuli'), ('c', 'yuwen')], default='a', max_length=100),
        ),
    ]
