# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pinfo',
            name='infoname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='read.Series'),
        ),
        migrations.AddField(
            model_name='period',
            name='infoname',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='read.Pinfo'),
        ),
        migrations.AddField(
            model_name='period',
            name='sname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='read.Series'),
        ),
        migrations.AddField(
            model_name='period',
            name='tag',
            field=models.ManyToManyField(default='', to='read.Tags'),
        ),
    ]
