# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinfo',
            name='infoname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
