# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=255)),
                ('purl', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
