# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_auto_20160704_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(default='', max_length=255)),
                ('surl', models.CharField(default='', max_length=255)),
                ('sface', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='sid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='period',
            name='pface',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='period',
            name='sid',
            field=models.IntegerField(default=0),
        ),
    ]
